# Generated by Django 3.0.3 on 2020-04-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject507', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('date', models.DateField()),
            ],
        ),
    ]
