# Generated by Django 3.0.3 on 2020-04-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject507', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
