# Generated by Django 3.0.3 on 2020-04-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject507', '0003_auto_20200417_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
